### ISSUE TITLE
table schema

### ISSUE THREAD

**Issue by kanekv** [cloudspannerecosystem/spanner-change-watcher#34]
Documentation doesn't mention what table schema should be, for this to work.
As I can tell it requires global commit timestamp column to exist?

**Comment by olavloite** [comment]
The only requirement is that each table that is monitored contains a column with `allow_commit_timestamp` set to `true`, and that the column is filled with the latest commit timestamp after each successful commit. The name of the column may be freely chosen. It is also not a requirement that all tables contain such a column, only the column that you want to monitor need it.
The `spanner-change-watcher` library will also automatically create a table named `LAST_SEEN_COMMIT_TIMESTAMPS` in your database to keep track of the last commit timestamp for each table that is being monitored. If you don't want this, you could configure a different table to be used. Have a look at the [samples](https://github.com/cloudspannerecosystem/spanner-change-watcher/blob/master/google-cloud-spanner-change-watcher/src/main/java/com/google/cloud/spanner/watcher/Samples.java) for more information and examples on this.

**Comment by kanekv** [comment]
@olavloite what if there are multiple columns with `allow_commit_timestamp`? 
Also I tried to make sharded queries on global timestamp column, but it seems optimizer really doesn't like it: https://stackoverflow.com/questions/61999247/is-it-possible-to-have-efficient-timestamp-ordered-queries-in-spanner
I have seen that you are using same type of query and it seems it's vastly inefficient (always does full table scan). It works if timestamp index is not sharded, but then spanner folks recommend against it (due to hotspots).

**Comment by olavloite** [comment]
@kanekv 

> what if there are multiple columns with `allow_commit_timestamp`?

That should not be possible. Only one column in a table can have the `allow_commit_timestamp` option set to true. If you already have a column with that option set, and then alter the table to set the option on a different column, the option will automatically be unset on the first column.

**Comment by olavloite** [comment]
> I have seen that you are using same type of query and it seems it's vastly inefficient (always does full table scan). It works if timestamp index is not sharded, but then spanner folks recommend against it (due to hotspots).

Yes, I know that is a potential problem at the moment, depending on the size of the table that you want to monitor. I'll look into possible solutions for that as well, but preferably without putting any strict requirements on exactly how your data model needs to be. E.g. if you just want to monitor one or more relatively small tables, then you should be fine without any additional indexes, and in other cases the library should be able to auto-detect which indexes are present and use those.

**Comment by kanekv** [comment]
> That should not be possible.

This doesn't seem to be correct, I am able to create tables with multiple commit timestamps allowed and it works (and sets them properly with commit timestamps).

**Comment by olavloite** [comment]
> This doesn't seem to be correct, I am able to create tables with multiple commit timestamps allowed and it works (and sets them properly with commit timestamps).

You seem to be right about that. I'm not sure where I got my (wrong) assumption from. The effect will in that case most probably be that it will use the first commit timestamp column it encounters, but I'll look into it.

**Comment by kanekv** [comment]
I think it needs explicit config: I am using some timestamp columns in mixed mode, sometimes setting to commit timestamp and sometimes overriding it. It will be just more flexible if it's configurable.

**Comment by kanekv** [comment]
>  I'll look into possible solutions for that as well, but preferably without putting any strict requirements on exactly how your data model needs to be.

I have created an issue about optimizer bugs: https://issuetracker.google.com/issues/157388602. Do you know of a better avenue to access spanner devs?

**Comment by kanekv** [comment]
I am particularly interested in this, because I have manually built exactly what you are doing here, watching a table and processing/pushing it to pubsub =)

**Comment by olavloite** [comment]
> > I'll look into possible solutions for that as well, but preferably without putting any strict requirements on exactly how your data model needs to be.
> 
> I have created an issue about optimizer bugs: https://issuetracker.google.com/issues/157388602. Do you know of a better avenue to access spanner devs?

For these kinds of questions, filing an issue/question there is the best way. As far as I can see, there is also already an answer to the specific question.

**Comment by olavloite** [comment]
> I am particularly interested in this, because I have manually built exactly what you are doing here, watching a table and processing/pushing it to pubsub =)

Always nice to hear :-) 
You're free to try this out, and while there might be some changes coming up that could break the current API a little bit, it should be quite limited. One thing to take into account though, is that this solution currently relies on the [async API](https://github.com/googleapis/java-spanner/pull/81) for the Java Spanner client library that has not yet been released.
That means that you would need to add a couple of custom build steps if you want to integrate into your existing application.
