### ISSUE TITLE
feat: support sharding for efficient indexing

### ISSUE THREAD

**Issue by olavloite** [cloudspannerecosystem/spanner-change-watcher#35]
The Spanner table tailers poll tables for the latest changes by searching for all records that have a commit timestamp greater than the previously seen last commit timestamp. This query will do a full table scan, unless the commit timestamp column is indexed. Indexing a commit timestamp column is however [highly discouraged](https://cloud.google.com/spanner/docs/whitepapers/optimizing-schema-design#anti-pattern_timestamp_ordering).

Instead of creating an index on only the commit timestamp column, it is recommended to prefix the index with an additional column containing a shard id. Each shard id can be a random value, but each should contain roughly the same number of entries.

`SpannerTableTailer` should be able to use shard ids and the corresponding index to optimize the polling queries. It should be possible to both assign a fixed set of shard ids to a tailer, as well as using a dynamically calculated shard id:
1. Fixed set: The `SpannerTableTailer` only polls for changes for the specific set of shard ids. The shard ids never change during the lifetime of the `SpannerTableTailer`.
1. Dynamic: The shard ids to use are determined based on the current system time and the last seen commit timestamp for a table. A fixed set of known transformations are supported for the conversion from system time to shard id, and the user application is responsible for setting the correct value. The tailer looks for new commit timestamps using the currently calculated shard id, and for a limited time for commit timestamps with the previous shard id. It also scans old shards directly after startup to pick up changes that might have happened while the tailer was not running.

The above means that a `CommitTimestampRepository` must be able to maintain and return the last seen commit timestamp per shard id.

The automatically calculated shard ids use the Spanner built-in functions for date formatting and hashing. A shard id is calculated using the following expression:

```sql
TO_BASE64(SHA512(FORMAT_DATE(shard_format, CURRENT_DATE('utc'))))
```

The `shard_format` is any supported input value for `FORMAT_DATE`: https://cloud.google.com/spanner/docs/date_functions#supported_format_elements_for_date

The above means that the smallest possible shard is one day. Larger shards can be created by choosing an appropriate date format. It also means that shards can be cyclic, but a user should ensure that the chosen cycle is longer than the possible down-time of the `SpannerTableTailer`. Creating shards based on the day of week (1-7) would for example mean that the `SpannerTableTailer` should never be offline for more than 1 week.

**Comment by olavloite** [comment]
cc @kanekv 
It is still a bit theoretical, but I have a global idea of how we could add (automatic) sharding to the solution. It would however still require your tables to contain a shard id and your application to also set the shard id for each insert/update.

**Comment by kanekv** [comment]
@olavloite This would work. I also found it's more efficient to have a worker per shard (looks like spanner poorly optimizes cross-shard select).

Thanks!
